### ISSUE TITLE
VerSe2019

### ISSUE THREAD

**Issue by FoilHao** [christianpayer/MedicalDataAugmentationTool#15]
Congratulations on ranking 1st in VerSe2019 challenge!
I've read your report and wonder when will your code be publicly available here?
That would be very helpful! Thanks in advance.

**Comment by christianpayer** [comment]
Thank you for the congratulations!
I finally managed to put the VerSe code online. You can find it under https://github.com/christianpayer/MedicalDataAugmentationTool-VerSe. It contains scripts for training, inference and also a Dockerfile that creates a Docker image with the pretrained models that we submitted to the challenge.
If you have any further questions, just to ask them either at the new repository or via mail.
