### ISSUE TITLE
SimpleITK version 2.0.0 breaks transformations/spatial/common.py

### ISSUE THREAD

**Issue by LucasPorto** [christianpayer/MedicalDataAugmentationTool#16]
Hi Christian,

The new release of SimpleITK breaks `create_composite`

https://github.com/christianpayer/MedicalDataAugmentationTool/blob/9c24ef4a173f01839dbb31455dad0f40e1e7bb88/transformations/spatial/common.py#L65

since `sitk.Transform` no longer has the `AddTransform` method.

**Comment by chouqin3** [comment]
how to solve it

**Comment by LucasPorto** [comment]
Downgrading SimpleITK (`pip install simpleitk==1.2.4`) solves the problem.

**Comment by christianpayer** [comment]
Downgrading should solve the problem. I also committed fixes such that the framework should now also work with SimpleITK 2.0.
