### ISSUE TITLE
Bug in translation.py

### ISSUE THREAD

**Issue by skrishnanv** [christianpayer/MedicalDataAugmentationTool#19]
hi,
looks like there is a bug in translation.py
Existing line around 248:
max_translation = [input_size[i] * input_spacing[i] - self.remove_border[i][i] for i in range(self.dim)]
should be ?
max_translation = [input_size[i] * input_spacing[i] - self.remove_border[i] for i in range(self.dim)]
thanks

**Comment by christianpayer** [comment]
You are right. One of my previous commits seemed to break this.
Thanks for spotting this issue! I just committed the fix.

**Comment by skrishnanv** [comment]
Thanks so much.

**Comment by skrishnanv** [comment]
thanks for the code!!
