### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'missing'

### ISSUE THREAD

**Issue by Xavier-cvpr** [christianpayer/MedicalDataAugmentationTool#2]
when i run the main.py in the  localization,it appear this error 

TypeError: __init__() got an unexpected keyword argument 'missing'

i do not know why?

**Comment by christianpayer** [comment]
There was a problem with LRUCache. The interface to LRUCache changed in more recent versions. I changed and committed the code to adapt to it.
