### ISSUE TITLE
Version of TensorFlow for running the project

### ISSUE THREAD

**Issue by hamedwaezi01-zz** [christianpayer/MedicalDataAugmentationTool#22]
Hi
After a while I want to rerun the localization network on some data. I am using Anaconda and would like to install the TensorFlow using it. What is the version that I should Install?
thanks in advance

**Comment by franzthaler** [comment]
The MedicalDataAugmentationTool provides an implementation in TensorFlow 1.X and TensorFlow 2.X, using `
tensorflow_train` and `tensorflow_train_v2` respectively. Whether you should use TensorFlow 1.X or 2.X depends on the experiment repository you are interested in, see the `list of experiment repositories` in the project description.
In both cases, I would recommend to use the latest stable version of TensorFlow which should work without problems.
