### ISSUE TITLE
using Convert3D,encounter a probelm 

### ISSUE THREAD

**Issue by Xavier-cvpr** [christianpayer/MedicalDataAugmentationTool#3]
for x in *_label.nii.gz;
    do c3d ${x} -replace 500 1 600 2 420 3 550 4 205 5 820 6 850 7 -o ${${x:r}:r}_sorted.nii.gz;
done

fault:
Exception caught of type class ConvertException
  Exception detail: Unable to read image for; IO factory can not create IO object.
Command C:/Program Files/Convert3D/bin/c3d.exe returned with error code -1

**Comment by christianpayer** [comment]
I don't know, where this error is coming from. It seems that there is a problem with c3d.
I created a new script (reorient.py), which should do the same things as the c3d commands. So you don't need to rely on c3d any more.

I hope this fixes the preprocessing for you!
